name: weread sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: WeRead to Notion
        uses: ./
        with:
          weread-api-key: ${{ secrets.WEREAD_API_KEY }}
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-page: ${{ secrets.NOTION_PAGE }}
          notion-database-id: ${{ secrets.NOTION_DATABASE_ID }}
